name: Build-MacOS

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-12]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.6
        with:
          script-name: main.py
          standalone: true
          onefile: true
          enable-plugins: pyside6
          macos-create-app-bundle: true
          disable-console: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/*
