name: Build-All-Platforms

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          standalone: true
          onefile: true
          enable-plugins: pyside6
          macos-create-app-bundle: true
          macos-app-version: 2.0
          assume-yes-for-download: true
          disable-console: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macBuild
          path: |
            build/*.bin
            build/*.app/**/*
