name: Build-MacOS

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-12
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Build Mac
        run: |
          bash build_mac.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MMAC Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/*
